spring:
  datasource: #数据库配置
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/zhongheshiji?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 15 #????????
      idle-timeout: 180000 #?????????????600000?10???
      maximum-pool-size: 25 #????????????10
      auto-commit: true #?????????????????????,????true
      max-lifetime: 1800000 #??????????????????0???????????1800000?30??
      connection-timeout: 30000 #?????????,??30???30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis: #redis配置
      host: 192.168.10.100
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100

mybatis: #mybatis配置
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml
